// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB60y8R3KU08KJBGT7fcD98GTHTegoTWwk',
    appId: '1:693337441759:web:235dd2047f2d45736bb06a',
    messagingSenderId: '693337441759',
    projectId: 'edp-smart-lock-app',
    authDomain: 'edp-smart-lock-app.firebaseapp.com',
    storageBucket: 'edp-smart-lock-app.appspot.com',
    measurementId: 'G-44PVBH23RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKF6DzK8BXe3MwgQtndZ3Ql82nfoMzAy4',
    appId: '1:693337441759:android:30879fc8b4cc7ca96bb06a',
    messagingSenderId: '693337441759',
    projectId: 'edp-smart-lock-app',
    storageBucket: 'edp-smart-lock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifI1KL1Ab4h5Qru1zEdxLOXMqi6Hrxms',
    appId: '1:693337441759:ios:e97fc71388ca3b356bb06a',
    messagingSenderId: '693337441759',
    projectId: 'edp-smart-lock-app',
    storageBucket: 'edp-smart-lock-app.appspot.com',
    iosClientId: '693337441759-p4kck4iqlk58sff9ad6p7rpac3ggr5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.edpSmartLockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifI1KL1Ab4h5Qru1zEdxLOXMqi6Hrxms',
    appId: '1:693337441759:ios:e97fc71388ca3b356bb06a',
    messagingSenderId: '693337441759',
    projectId: 'edp-smart-lock-app',
    storageBucket: 'edp-smart-lock-app.appspot.com',
    iosClientId: '693337441759-p4kck4iqlk58sff9ad6p7rpac3ggr5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.edpSmartLockApp',
  );
}
